name: flutter_practice_one

packages:
  - apps/**

scripts: 
  #Setup env for puro
  postbootstrap: >
    melos exec -- puro flutter pub get && 
    pub global activate puro 
  #Run app
  run_app: 
    run: melos exec -- puro flutter run lib/main.dart 
    description: Run `puro` on all packages.
    packageFilters: 
      scope: 
        - fitness_app

  analyze: 
    run: melos exec -- puro flutter analyze .
    description: Run `dart analyze` on all packages.
    packageFilters: 
      scope: 
        - fitness_app
        - fitness_ui
  