name: flutter_practice_one

packages:
  - apps/*

scripts: 
  analyze: 
    run: melos exec -- puro flutter analyze .
    description: Run `dart analyze` on all packages.
    packageFilters: 
      scope: 
        - fitness_app
        - fitness_ui
  