name: api_client
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: 
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  mockito: ^5.4.0
  
flutter: null
