name: fitness_widgetbook
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:

  build_runner: ^2.4.7
  device_preview: ^1.1.0

  fitness_app:
    path: ../fitness_app

  fitness_ui:
    path: ../fitness_ui

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: com.mastertipsy.flutter_localization
        pluginClass: FlutterLocalizationPlugin
      ios:
        pluginClass: FlutterLocalizationPlugin
